"""MLflow artifacts for fraud promotion gate."""

import os
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from typing import Dict

from fraud.evaluation.metrics import compute_fraud_metrics, generate_evaluation_artifacts


def generate_mlflow_artifacts(
    model,
    X_test: pd.DataFrame,
    y_test: pd.Series,
    output_dir: str
):
    """
    Generate all MLflow artifacts as specified for fraud
    
    Artifacts:
    - metrics.json
    - confusion_matrix.png
    - pr_curve.png
    - roc_curve.png
    - calibration_curve.png
    - precision_recall_curve.png
    - feature_importance_shap.png
    - policy_decision_curve.png
    - data_quality_report.json
    - drift_baseline.json
    - model_card.md
    """
    os.makedirs(output_dir, exist_ok=True)
    
    # Predictions
    y_pred_proba = model.predict_proba(X_test)
    y_pred = model.predict(X_test)
    
    # 1. metrics.json
    metrics = compute_fraud_metrics(y_test, y_pred_proba)
    with open(os.path.join(output_dir, "metrics.json"), "w", encoding="utf-8") as f:
        json.dump(metrics, f, indent=2)
    
    # 2-6. Already generated by generate_evaluation_artifacts
    # (confusion_matrix.png, pr_curve.png, roc_curve.png, calibration_curve.png, precision_recall_curve.png)
    generate_evaluation_artifacts(y_test, y_pred_proba, output_dir)
    
    # 7. feature_importance_shap.png
    if hasattr(model, 'model') and hasattr(model.model, 'feature_importance'):
        generate_feature_importance_plot(model, X_test, output_dir)
    
    # 8. policy_decision_curve.png
    generate_policy_decision_curve(y_test, y_pred_proba, output_dir)
    
    # 9. data_quality_report.json
    generate_data_quality_report(X_test, output_dir)
    
    # 10. drift_baseline.json
    generate_drift_baseline(X_test, y_pred_proba, output_dir)
    
    # 11. model_card.md
    generate_model_card(model, metrics, output_dir)


def generate_feature_importance_plot(model, X_test: pd.DataFrame, output_dir: str):
    """Generate feature importance plot"""
    try:
        if model.model_type == "lightgbm":
            import lightgbm as lgb
            if isinstance(model.model, lgb.Booster):
                importance = model.model.feature_importance(importance_type='gain')
                feature_names = model.feature_names or X_test.columns.tolist()
                
                # Sort by importance
                indices = np.argsort(importance)[::-1][:20]  # Top 20
                
                plt.figure(figsize=(10, 8))
                plt.barh(range(len(indices)), importance[indices])
                plt.yticks(range(len(indices)), [feature_names[i] for i in indices])
                plt.xlabel('Feature Importance (Gain)')
                plt.title('Feature Importance (Top 20)')
                plt.gca().invert_yaxis()
                plt.tight_layout()
                plt.savefig(os.path.join(output_dir, "feature_importance_shap.png"))
                plt.close()
    except Exception as e:
        print(f"Could not generate feature importance plot: {e}")


def generate_policy_decision_curve(
    y_true: pd.Series,
    y_pred_proba: np.ndarray,
    output_dir: str
):
    """Generate policy decision curve (decision rate vs threshold)"""
    thresholds = np.linspace(0, 1, 100)
    
    if y_pred_proba.ndim > 1:
        y_pred_proba = y_pred_proba[:, 0] if y_pred_proba.shape[1] == 1 else y_pred_proba[:, 1]
    
    approve_rates = []
    reject_rates = []
    manual_review_rates = []
    
    for threshold in thresholds:
        # Simple policy: low risk approve, high risk reject, medium risk manual review
        approve = (y_pred_proba < 0.5).mean()
        reject = (y_pred_proba >= 0.9).mean()
        manual_review = ((y_pred_proba >= 0.5) & (y_pred_proba < 0.9)).mean()
        
        approve_rates.append(approve)
        reject_rates.append(reject)
        manual_review_rates.append(manual_review)
    
    plt.figure(figsize=(10, 6))
    plt.plot(thresholds, approve_rates, label='Approve Rate', linewidth=2)
    plt.plot(thresholds, reject_rates, label='Reject Rate', linewidth=2)
    plt.plot(thresholds, manual_review_rates, label='Manual Review Rate', linewidth=2)
    plt.xlabel('Risk Score Threshold')
    plt.ylabel('Decision Rate')
    plt.title('Policy Decision Curve')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(output_dir, "policy_decision_curve.png"))
    plt.close()


def generate_data_quality_report(X_test: pd.DataFrame, output_dir: str):
    """Generate data quality report"""
    report = {
        "missing_rate": (X_test.isnull().sum() / len(X_test)).to_dict(),
        "schema_drift": 0,  # Would check against schema
        "domain_set_violations": 0  # Would check domain sets
    }
    
    with open(os.path.join(output_dir, "data_quality_report.json"), "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)


def generate_drift_baseline(
    X_test: pd.DataFrame,
    y_pred_proba: np.ndarray,
    output_dir: str
):
    """Generate drift baseline"""
    if y_pred_proba.ndim > 1:
        y_pred_proba = y_pred_proba[:, 0] if y_pred_proba.shape[1] == 1 else y_pred_proba[:, 1]
    
    baseline = {
        "feature_distributions": {
            col: {
                "mean": float(X_test[col].mean()),
                "std": float(X_test[col].std()),
                "percentiles": {
                    "p10": float(X_test[col].quantile(0.1)),
                    "p50": float(X_test[col].quantile(0.5)),
                    "p90": float(X_test[col].quantile(0.9))
                }
            }
            for col in X_test.select_dtypes(include=[np.number]).columns
        },
        "score_distribution": {
            "mean": float(y_pred_proba.mean()),
            "std": float(y_pred_proba.std()),
            "percentiles": {
                "p10": float(np.percentile(y_pred_proba, 10)),
                "p50": float(np.percentile(y_pred_proba, 50)),
                "p90": float(np.percentile(y_pred_proba, 90))
            }
        }
    }
    
    with open(os.path.join(output_dir, "drift_baseline.json"), "w", encoding="utf-8") as f:
        json.dump(baseline, f, indent=2)


def generate_model_card(model, metrics: Dict, output_dir: str):
    """Generate model card"""
    card = f"""# Model Card: Fraud Risk Scoring Model

## Model Details
- Model Type: {model.model_type}
- Calibration: {model.calibrate}
- Feature Set Version: fs_fraud_v1

## Performance Metrics
- AUC: {metrics.get('auc', 'N/A'):.4f}
- PR-AUC: {metrics.get('pr_auc', 'N/A'):.4f}
- Brier Score: {metrics.get('brier', 'N/A'):.4f}
- ECE: {metrics.get('ece', 'N/A'):.4f}
- TopK Precision@5%: {metrics.get('topk_precision_5pct', 'N/A'):.4f}
- TopK Precision@10%: {metrics.get('topk_precision_10pct', 'N/A'):.4f}
- Recall@Precision=90%: {metrics.get('recall_at_precision_90', 'N/A'):.4f}
- FPR@Recall=80%: {metrics.get('fpr_at_recall_80', 'N/A'):.4f}

## Intended Use
Predict fraud risk score (0-1) for transactions. Used with policy engine to make APPROVE/REJECT/MANUAL_REVIEW decisions.

## SLO
- p95 latency: ≤ 80ms
- 5xx error rate: ≤ 0.1%

## Limitations
- Trained on historical data, may not generalize to future distributions
- Requires feature store to be up-to-date
- Real-time features (transaction_count_1h) require low-latency feature store
"""
    
    with open(os.path.join(output_dir, "model_card.md"), "w", encoding="utf-8") as f:
        f.write(card)
